# Dependencies
markdown:         redcarpet
highlighter:      pygments

gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Daniel Coutts
tagline:          Developer
description:      I am 3rd year computer science student at Newcastle University, and I am currently working as an Android app developer at Gospelware.
# url:              http://hyde.getpoole.com
baseurl:          /

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

github:           https://github.com/DanielCoutts
linkedin:         https://linkedin.com/in/daniel-coutts-b4401282
twitter:          https://twitter.com/elasticdonut
cv:               assets/CV.pdf
